name: Run Selenium Script Every 20 minutes

on:
  schedule:
    - cron: '*/20 * * * *'  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python .github/workflows/main.py
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
    - name: Commit updated data (if needed)
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data.txt || true
        git diff --quiet && git diff --staged --quiet || git commit -m "Update tracked number"
        git push
